default_language_version:
  python: 3.13.9

default_stages: [commit]

repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: 'v6.0.0'
  #   hooks:
  #     - id: no-commit-to-branch
  #       args: [--branch, main]
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-added-large-files
  #       args: ["--maxkb=500"]
  #     - id: check-json
  #     - id: check-toml

  # - repo: https://github.com/pycqa/isort
  #   rev: '7.0.0'
  #   hooks:
  #     - id: isort
  #       args: ["--profile=black", "--line-length=120"]

- repo: https://github.com/psf/black
  rev: '25.9.0'
  hooks:
    - id: black
      args: [--line-length=120]
    - id: black-jupyter
      args: [--line-length=120]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.2'
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      additional_dependencies: ['types-PyYAML']

- repo: https://github.com/executablebooks/mdformat.git
  rev: '1.0.0'
  hooks:
    - id: mdformat

- repo: https://github.com/kynan/nbstripout
  rev: '0.8.1'
  hooks:
  - id: nbstripout

- repo: https://github.com/s-weigand/flake8-nb
  rev: 'v0.5.3'
  hooks:
  - id: flake8-nb
    args: ["--ignore=E203,W503"]
