default_language_version:
  python: 3.10.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: no-commit-to-branch
      args:
        [--branch, main]
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
    - id: check-toml

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile=black", "--line-length=79"]

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
      args:
        [--line-length=79]
    - id: black-jupyter
      args:
        [--line-length=79]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      additional_dependencies: ['types-PyYAML']

- repo: https://github.com/executablebooks/mdformat.git
  rev: 0.7.16
  hooks:
    - id: mdformat

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout

- repo: https://github.com/s-weigand/flake8-nb
  rev: v0.5.2
  hooks:
  - id: flake8-nb
    args: ["--ignore=E203,W503"]
